### PR TITLE
use a built in method to parse version strings.

### PR DESCRIPTION
**Pull request by djeebus**
the old parsing doesn't work for pyramid 1.10+

### CODE REVIEW

**Comment by ergo** [comment]
Hey @djeebus can you add yourself to AUTHORS file so I can merge this PR?
Also the tests are failing so we probably need to install additional packages during travis builds.

**Comment by ergo** [comment]
As for py3 support, I wonder if it wouldn't be better/easier to run futurize on the codebase and make it 2.x compatible where required.

**Comment by djeebus** [comment]
Took care of the authors file and fixed the tests (well, hopefully fixed the tests). Not sure about futurize, I've never used it.

**Comment by ergo** [comment]
No problem, I'll try to look at this soon and merge.

https://python-future.org/ - this is the lib I had in mind.
In the future I'd like the client to actually run from single codebase - without resorting to 2to3 conversion on install.

**Comment by djeebus** [comment]
I could take a look in the future (no pun intended) =P

**Comment by ergo** [comment]
Thank you!

**Pull request merged**
